# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reco_social_related_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reco_social_related_info.proto',
  package='ks.reco',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1ereco_social_related_info.proto\x12\x07ks.reco\"9\n\x10\x43ommonFriendList\x12\x11\n\tauthor_id\x18\x01 \x01(\x04\x12\x12\n\nfriend_ids\x18\x02 \x03(\x04\"J\n\x11SocialRelatedInfo\x12\x35\n\x12\x63ommon_friend_list\x18\x01 \x03(\x0b\x32\x19.ks.reco.CommonFriendListb\x06proto3')
)




_COMMONFRIENDLIST = _descriptor.Descriptor(
  name='CommonFriendList',
  full_name='ks.reco.CommonFriendList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='author_id', full_name='ks.reco.CommonFriendList.author_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='friend_ids', full_name='ks.reco.CommonFriendList.friend_ids', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=100,
)


_SOCIALRELATEDINFO = _descriptor.Descriptor(
  name='SocialRelatedInfo',
  full_name='ks.reco.SocialRelatedInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_friend_list', full_name='ks.reco.SocialRelatedInfo.common_friend_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=176,
)

_SOCIALRELATEDINFO.fields_by_name['common_friend_list'].message_type = _COMMONFRIENDLIST
DESCRIPTOR.message_types_by_name['CommonFriendList'] = _COMMONFRIENDLIST
DESCRIPTOR.message_types_by_name['SocialRelatedInfo'] = _SOCIALRELATEDINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonFriendList = _reflection.GeneratedProtocolMessageType('CommonFriendList', (_message.Message,), dict(
  DESCRIPTOR = _COMMONFRIENDLIST,
  __module__ = 'reco_social_related_info_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.CommonFriendList)
  ))
_sym_db.RegisterMessage(CommonFriendList)

SocialRelatedInfo = _reflection.GeneratedProtocolMessageType('SocialRelatedInfo', (_message.Message,), dict(
  DESCRIPTOR = _SOCIALRELATEDINFO,
  __module__ = 'reco_social_related_info_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.SocialRelatedInfo)
  ))
_sym_db.RegisterMessage(SocialRelatedInfo)


# @@protoc_insertion_point(module_scope)
