# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reco_browse_set.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reco_browse_set.proto',
  package='ks.reco',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15reco_browse_set.proto\x12\x07ks.reco\"n\n\rBrowseSetInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08photo_id\x18\x02 \x03(\x03\x12\r\n\x05\x64\x65lta\x18\x03 \x03(\x03\x12\r\n\x05index\x18\x04 \x03(\x05\x12\r\n\x05pages\x18\x06 \x01(\x05J\x04\x08\x05\x10\x06R\x05llsid\"U\n\nBrowseItem\x12\x10\n\x08photo_id\x18\x01 \x01(\x04\x12\x0f\n\x07\x65xp_tag\x18\x02 \x01(\x05\x12$\n\tshow_type\x18\x03 \x01(\x0e\x32\x11.ks.reco.ShowType\"Z\n\x0c\x42rowseScreen\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05llsid\x18\x02 \x01(\x03\x12(\n\x0b\x62rowse_item\x18\x03 \x03(\x0b\x32\x13.ks.reco.BrowseItem*>\n\x08ShowType\x12\x0f\n\x0b\x42ROWSE_SHOW\x10\x00\x12\r\n\tREAL_SHOW\x10\x01\x12\x12\n\x0e\x44ISCARDED_SHOW\x10\x02\x62\x06proto3')
)

_SHOWTYPE = _descriptor.EnumDescriptor(
  name='ShowType',
  full_name='ks.reco.ShowType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BROWSE_SHOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REAL_SHOW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCARDED_SHOW', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=325,
  serialized_end=387,
)
_sym_db.RegisterEnumDescriptor(_SHOWTYPE)

ShowType = enum_type_wrapper.EnumTypeWrapper(_SHOWTYPE)
BROWSE_SHOW = 0
REAL_SHOW = 1
DISCARDED_SHOW = 2



_BROWSESETINFO = _descriptor.Descriptor(
  name='BrowseSetInfo',
  full_name='ks.reco.BrowseSetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ks.reco.BrowseSetInfo.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='photo_id', full_name='ks.reco.BrowseSetInfo.photo_id', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta', full_name='ks.reco.BrowseSetInfo.delta', index=2,
      number=3, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='ks.reco.BrowseSetInfo.index', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pages', full_name='ks.reco.BrowseSetInfo.pages', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=144,
)


_BROWSEITEM = _descriptor.Descriptor(
  name='BrowseItem',
  full_name='ks.reco.BrowseItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='photo_id', full_name='ks.reco.BrowseItem.photo_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exp_tag', full_name='ks.reco.BrowseItem.exp_tag', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_type', full_name='ks.reco.BrowseItem.show_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=231,
)


_BROWSESCREEN = _descriptor.Descriptor(
  name='BrowseScreen',
  full_name='ks.reco.BrowseScreen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ks.reco.BrowseScreen.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='llsid', full_name='ks.reco.BrowseScreen.llsid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='browse_item', full_name='ks.reco.BrowseScreen.browse_item', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=323,
)

_BROWSEITEM.fields_by_name['show_type'].enum_type = _SHOWTYPE
_BROWSESCREEN.fields_by_name['browse_item'].message_type = _BROWSEITEM
DESCRIPTOR.message_types_by_name['BrowseSetInfo'] = _BROWSESETINFO
DESCRIPTOR.message_types_by_name['BrowseItem'] = _BROWSEITEM
DESCRIPTOR.message_types_by_name['BrowseScreen'] = _BROWSESCREEN
DESCRIPTOR.enum_types_by_name['ShowType'] = _SHOWTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrowseSetInfo = _reflection.GeneratedProtocolMessageType('BrowseSetInfo', (_message.Message,), dict(
  DESCRIPTOR = _BROWSESETINFO,
  __module__ = 'reco_browse_set_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.BrowseSetInfo)
  ))
_sym_db.RegisterMessage(BrowseSetInfo)

BrowseItem = _reflection.GeneratedProtocolMessageType('BrowseItem', (_message.Message,), dict(
  DESCRIPTOR = _BROWSEITEM,
  __module__ = 'reco_browse_set_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.BrowseItem)
  ))
_sym_db.RegisterMessage(BrowseItem)

BrowseScreen = _reflection.GeneratedProtocolMessageType('BrowseScreen', (_message.Message,), dict(
  DESCRIPTOR = _BROWSESCREEN,
  __module__ = 'reco_browse_set_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.BrowseScreen)
  ))
_sym_db.RegisterMessage(BrowseScreen)


# @@protoc_insertion_point(module_scope)
