# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reco_debug_log.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reco_debug_log.proto',
  package='ks.reco',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14reco_debug_log.proto\x12\x07ks.reco\"\xf5\x01\n\x0cRecoDebugLog\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\r\n\x05llsid\x18\x03 \x01(\x03\x12\x0f\n\x07item_id\x18\x04 \x03(\x04\x12\x11\n\titem_type\x18\x05 \x03(\r\x12\x13\n\x0bsource_type\x18\x06 \x03(\r\x12\r\n\x05score\x18\x07 \x03(\x01\x12\x12\n\nstage_flag\x18\x08 \x01(\t\x12\x1c\n\x14processor_class_name\x18\t \x01(\t\x12\x14\n\x0crequest_type\x18\n \x01(\x05\x12\x10\n\x08log_time\x18\x0b \x01(\x04\x12\x10\n\x08\x62usiness\x18\x0c \x01(\x05\x62\x06proto3')
)




_RECODEBUGLOG = _descriptor.Descriptor(
  name='RecoDebugLog',
  full_name='ks.reco.RecoDebugLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ks.reco.RecoDebugLog.user_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ks.reco.RecoDebugLog.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='llsid', full_name='ks.reco.RecoDebugLog.llsid', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='ks.reco.RecoDebugLog.item_id', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_type', full_name='ks.reco.RecoDebugLog.item_type', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_type', full_name='ks.reco.RecoDebugLog.source_type', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='ks.reco.RecoDebugLog.score', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stage_flag', full_name='ks.reco.RecoDebugLog.stage_flag', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processor_class_name', full_name='ks.reco.RecoDebugLog.processor_class_name', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_type', full_name='ks.reco.RecoDebugLog.request_type', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_time', full_name='ks.reco.RecoDebugLog.log_time', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='business', full_name='ks.reco.RecoDebugLog.business', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=279,
)

DESCRIPTOR.message_types_by_name['RecoDebugLog'] = _RECODEBUGLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecoDebugLog = _reflection.GeneratedProtocolMessageType('RecoDebugLog', (_message.Message,), dict(
  DESCRIPTOR = _RECODEBUGLOG,
  __module__ = 'reco_debug_log_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.RecoDebugLog)
  ))
_sym_db.RegisterMessage(RecoDebugLog)


# @@protoc_insertion_point(module_scope)
