# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reco_user_profile_base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reco_user_profile_base.proto',
  package='ks.reco',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1creco_user_profile_base.proto\x12\x07ks.reco\"\x9e\x03\n\x0e\x45xternalAction\x12\x16\n\x0eserver_time_ms\x18\x01 \x01(\x03\x12\x33\n\tpage_type\x18\x02 \x01(\x0e\x32 .ks.reco.ExternalAction.PageType\x12\x37\n\x0b\x61\x63tion_type\x18\x03 \x01(\x0e\x32\".ks.reco.ExternalAction.ActionType\x12\x19\n\x11\x64\x65vice_resolution\x18\x04 \x01(\t\x12\x11\n\tclient_ip\x18\x05 \x01(\t\x12\x10\n\x08photo_id\x18\x06 \x01(\x04\x12\x11\n\tauthor_id\x18\x07 \x01(\x04\x12\x17\n\x0f\x66orward_user_id\x18\x08 \x01(\x04\x12\x10\n\x08platform\x18\t \x01(\t\x12\x15\n\rgoto_position\x18\n \x01(\t\";\n\x08PageType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\t\n\x05PHOTO\x10\x01\x12\x08\n\x04USER\x10\x02\x12\x08\n\x04LIVE\x10\x03\"4\n\nActionType\x12\x12\n\x0eUNKNOWN_ACTION\x10\x00\x12\x08\n\x04VIEW\x10\x01\x12\x08\n\x04GOTO\x10\x02\"\xcd\x03\n\x0bJiGuangDict\x12\x17\n\x0f\x63pl_indm_gend_s\x18\x01 \x01(\t\x12\x17\n\x0f\x63pl_indm_age_c5\x18\x02 \x01(\t\x12\x1a\n\x12\x63pl_indm_edu_level\x18\x03 \x01(\t\x12\x17\n\x0f\x63pl_indm_underg\x18\x04 \x01(\t\x12\x19\n\x11gbm_bhm_purb_supr\x18\x05 \x03(\t\x12\x19\n\x11gbm_bhm_purb_conp\x18\x06 \x03(\t\x12\x19\n\x11\x66im_fism_conl_cir\x18\x07 \x01(\t\x12\x15\n\rfim_fism_incl\x18\x08 \x01(\t\x12\x15\n\rdesire_travel\x18\t \x01(\t\x12 \n\x18\x61pp_hoby_rebate_shopping\x18\n \x01(\x01\x12\x1d\n\x15\x61pp_hoby_smote_office\x18\x0b \x01(\x01\x12\x1b\n\x13\x61pp_hoby_self_photo\x18\x0c \x01(\x01\x12\x1b\n\x13\x61pp_hoby_hot_social\x18\r \x01(\x01\x12\x14\n\x0c\x61pp_hoby_job\x18\x0e \x01(\x01\x12\x15\n\rgbm_hbm_s_tag\x18\x0f \x03(\t\x12\x1c\n\x14gbm_hbm_s_confidence\x18\x10 \x03(\x01\x12\x12\n\nis_success\x18\x11 \x01(\x08\x62\x06proto3')
)



_EXTERNALACTION_PAGETYPE = _descriptor.EnumDescriptor(
  name='PageType',
  full_name='ks.reco.ExternalAction.PageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHOTO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIVE', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=343,
  serialized_end=402,
)
_sym_db.RegisterEnumDescriptor(_EXTERNALACTION_PAGETYPE)

_EXTERNALACTION_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='ks.reco.ExternalAction.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ACTION', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIEW', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOTO', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=404,
  serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_EXTERNALACTION_ACTIONTYPE)


_EXTERNALACTION = _descriptor.Descriptor(
  name='ExternalAction',
  full_name='ks.reco.ExternalAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_time_ms', full_name='ks.reco.ExternalAction.server_time_ms', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_type', full_name='ks.reco.ExternalAction.page_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_type', full_name='ks.reco.ExternalAction.action_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_resolution', full_name='ks.reco.ExternalAction.device_resolution', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_ip', full_name='ks.reco.ExternalAction.client_ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='photo_id', full_name='ks.reco.ExternalAction.photo_id', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author_id', full_name='ks.reco.ExternalAction.author_id', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forward_user_id', full_name='ks.reco.ExternalAction.forward_user_id', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='ks.reco.ExternalAction.platform', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goto_position', full_name='ks.reco.ExternalAction.goto_position', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXTERNALACTION_PAGETYPE,
    _EXTERNALACTION_ACTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=456,
)


_JIGUANGDICT = _descriptor.Descriptor(
  name='JiGuangDict',
  full_name='ks.reco.JiGuangDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpl_indm_gend_s', full_name='ks.reco.JiGuangDict.cpl_indm_gend_s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpl_indm_age_c5', full_name='ks.reco.JiGuangDict.cpl_indm_age_c5', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpl_indm_edu_level', full_name='ks.reco.JiGuangDict.cpl_indm_edu_level', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpl_indm_underg', full_name='ks.reco.JiGuangDict.cpl_indm_underg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gbm_bhm_purb_supr', full_name='ks.reco.JiGuangDict.gbm_bhm_purb_supr', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gbm_bhm_purb_conp', full_name='ks.reco.JiGuangDict.gbm_bhm_purb_conp', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fim_fism_conl_cir', full_name='ks.reco.JiGuangDict.fim_fism_conl_cir', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fim_fism_incl', full_name='ks.reco.JiGuangDict.fim_fism_incl', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desire_travel', full_name='ks.reco.JiGuangDict.desire_travel', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_hoby_rebate_shopping', full_name='ks.reco.JiGuangDict.app_hoby_rebate_shopping', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_hoby_smote_office', full_name='ks.reco.JiGuangDict.app_hoby_smote_office', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_hoby_self_photo', full_name='ks.reco.JiGuangDict.app_hoby_self_photo', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_hoby_hot_social', full_name='ks.reco.JiGuangDict.app_hoby_hot_social', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_hoby_job', full_name='ks.reco.JiGuangDict.app_hoby_job', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gbm_hbm_s_tag', full_name='ks.reco.JiGuangDict.gbm_hbm_s_tag', index=14,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gbm_hbm_s_confidence', full_name='ks.reco.JiGuangDict.gbm_hbm_s_confidence', index=15,
      number=16, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_success', full_name='ks.reco.JiGuangDict.is_success', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=920,
)

_EXTERNALACTION.fields_by_name['page_type'].enum_type = _EXTERNALACTION_PAGETYPE
_EXTERNALACTION.fields_by_name['action_type'].enum_type = _EXTERNALACTION_ACTIONTYPE
_EXTERNALACTION_PAGETYPE.containing_type = _EXTERNALACTION
_EXTERNALACTION_ACTIONTYPE.containing_type = _EXTERNALACTION
DESCRIPTOR.message_types_by_name['ExternalAction'] = _EXTERNALACTION
DESCRIPTOR.message_types_by_name['JiGuangDict'] = _JIGUANGDICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExternalAction = _reflection.GeneratedProtocolMessageType('ExternalAction', (_message.Message,), dict(
  DESCRIPTOR = _EXTERNALACTION,
  __module__ = 'reco_user_profile_base_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.ExternalAction)
  ))
_sym_db.RegisterMessage(ExternalAction)

JiGuangDict = _reflection.GeneratedProtocolMessageType('JiGuangDict', (_message.Message,), dict(
  DESCRIPTOR = _JIGUANGDICT,
  __module__ = 'reco_user_profile_base_pb2'
  # @@protoc_insertion_point(class_scope:ks.reco.JiGuangDict)
  ))
_sym_db.RegisterMessage(JiGuangDict)


# @@protoc_insertion_point(module_scope)
